
browserslist.files.inspection.group.display.name=Browserslist
browserslist.inspection.missed.not.dead.move.use.quickfix=Move existing 'not dead' query
browserslist.inspection.missed.not.dead.problem.descriptor=Missing 'not dead' query after last N query
browserslist.inspection.missed.not.dead.add.use.quickfix=Add 'not dead' query
