
browserslist.files.inspection.group.display.name=Browserslist
browserslist.inspection.missed.not.dead.move.use.quickfix=Move existing 'not dead' query
browserslist.inspection.missed.not.dead.problem.descriptor=Missing 'not dead' query after last N query
browserslist.inspection.missed.not.dead.add.use.quickfix=Add 'not dead' query
browserslist.codevision.see.stats.on.browsersl.ist.hint=See stats on browsersl.ist
browserslist.codevision.stats.description=Shows audience coverage in a global region according to an installed browserslist version and a link to https://browsersl.ist for detailed statistics.
