{
  generate=[java="8"]
  parserClass="com.github.aleksandrsl.intellijbrowserslist.parser.BrowserslistParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Browserslist"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.aleksandrsl.intellijbrowserslist.psi"
  psiImplPackage="com.github.aleksandrsl.intellijbrowserslist.psi.impl"

  elementTypeHolderClass="com.github.aleksandrsl.intellijbrowserslist.psi.BrowserslistTypes"
  elementTypeClass="com.github.aleksandrsl.intellijbrowserslist.psi.BrowserslistElementType"
  tokenTypeClass="com.github.aleksandrsl.intellijbrowserslist.psi.BrowserslistTokenType"

  tokens=[
    EOL="regexp:\R"
    LBRACKET="["
    RBRACKET="]"
    IN="in"
    PERCENT="regexp:\d*\.?\d+%"
    DEFAULTS="defaults"
    COMPARE="regexp:>=?|<=?"
    space="regexp:\s+"
  ]
}

browserslistFile ::= item_*

private item_ ::= (DEFAULTS|query_|COMMENT|EOL)

private query_ ::= (statsQuery | lastQuery | unreleasedQuery) EOL
//section ::= LBRACKET IDENTIFIER (WHITESPACE IDENTIFIER)* RBRACKET CRLF query*
statsQuery ::= COMPARE PERCENT (IN STATS)?
lastQuery ::= LAST INTEGER TARGET? MAJOR? VERSIONS
unreleasedQuery ::= UNRELEASED TARGET? VERSIONS
